[package]
name = "lune-roblox"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
name = "lune_roblox"
path = "src/lib.rs"

[dependencies]
mlua.workspace = true
once_cell.workspace = true

glam = "0.23"
rand = "0.8"
thiserror = "1.0"

rbx_binary = { git = "https://github.com/rojo-rbx/rbx-dom", rev = "86f63d68261eaa18697c21053c4f4dbcb6a8ad08" }
rbx_dom_weak = { git = "https://github.com/rojo-rbx/rbx-dom", rev = "86f63d68261eaa18697c21053c4f4dbcb6a8ad08" }
rbx_reflection = { git = "https://github.com/rojo-rbx/rbx-dom", rev = "86f63d68261eaa18697c21053c4f4dbcb6a8ad08" }
rbx_reflection_database = { git = "https://github.com/rojo-rbx/rbx-dom", rev = "86f63d68261eaa18697c21053c4f4dbcb6a8ad08" }
rbx_xml = { git = "https://github.com/rojo-rbx/rbx-dom", rev = "86f63d68261eaa18697c21053c4f4dbcb6a8ad08" }

[dev-dependencies]
anyhow = "1.0"
