[package]
name = "lune-roblox"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
name = "lune_roblox"
path = "src/lib.rs"

[dependencies]
mlua.workspace = true

base64 = "0.21"
glam = "0.23"
rand = "0.8"
thiserror = "1.0"

rbx_binary = { git = "https://github.com/rojo-rbx/rbx-dom", rev = "88aed24a127d489431265ed42b408b003e08c025" }
rbx_dom_weak = { git = "https://github.com/rojo-rbx/rbx-dom", rev = "88aed24a127d489431265ed42b408b003e08c025" }
rbx_reflection = { git = "https://github.com/rojo-rbx/rbx-dom", rev = "88aed24a127d489431265ed42b408b003e08c025" }
rbx_reflection_database = { git = "https://github.com/rojo-rbx/rbx-dom", rev = "88aed24a127d489431265ed42b408b003e08c025" }
rbx_xml = { git = "https://github.com/rojo-rbx/rbx-dom", rev = "88aed24a127d489431265ed42b408b003e08c025" }

[dev-dependencies]
anyhow = "1.0"
