[package]
name = "lune"
version = "0.1.1"
edition = "2021"
license = "MPL 2.0"
repository = "https://github.com/filiptibell/lune"
description = "A Luau script runner"
keywords = ["cli", "lua", "luau", "scripts"]
categories = ["command-line-interface"]

[[bin]]
name = "lune"
path = "src/cli/main.rs"

[lib]
name = "lune"
path = "src/lib/lib.rs"

[profile.release]
strip = true # Automatically strip symbols from the binary.
opt-level = "z" # Optimize for size.
lto = true # Enable link-time optimization
panic = "abort" # Remove extra panic info

[dependencies]

anyhow = "1.0.68"
os_str_bytes = "6.4.1"
serde_json = "1.0.91"
smol = "1.3.0"
ureq = "2.6.2"

clap = { version = "4.1.1", features = ["derive"] }
mlua = { version = "0.8.7", features = ["luau", "async", "serialize"] }
serde = { version = "1.0.152", features = ["derive"] }
