[workspace]

members = ["packages/cli", "packages/lib"]
default-members = ["packages/cli"]

[workspace.package]
version = "0.3.0"
edition = "2021"
license = "MPL-2.0"
repository = "https://github.com/filiptibell/lune"
description = "A Luau script runner"
readme = "README.md"
keywords = ["cli", "lua", "luau", "scripts"]
categories = ["command-line-interface"]

[profile.release]
strip = true # Automatically strip symbols from the binary.
opt-level = "z" # Optimize for size.
lto = true # Enable link-time optimization
panic = "abort" # Remove extra panic info

[workspace.dependencies]

serde_json = "1.0.91"

serde = { version = "1.0.152", features = ["derive"] }
tokio = { version = "1.24.2", features = ["full"] }

[workspace.dependencies.reqwest]
version = "0.11.14"
default-features = false
features = ["rustls-tls"]
