[package]
name = "lune"
version = "0.0.4"
edition = "2021"
license = "MPL 2.0"
repository = "https://github.com/filiptibell/lune"
description = "A Luau script runner"
keywords = ["cli", "lua", "luau", "scripts"]
categories = ["command-line-interface"]

[[bin]]
name = "lune"
path = "src/main.rs"

[profile.release]
strip = true # Automatically strip symbols from the binary.
opt-level = "z" # Optimize for size.
lto = true # Enable link-time optimization
panic = "abort" # Remove extra panic info

[dependencies]
anyhow = { version = "1.0.68" }
clap = { version = "4.1.1", features = ["derive"] }
mlua = { version = "0.8.7", features = ["luau", "async", "serialize"] }
os_str_bytes = "6.4.1"
reqwest = { version = "0.11.13", features = ["gzip", "deflate"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = { version = "1.0.91" }
tokio = { version = "1.24.2", features = ["full"] }
