[package]
name = "lune"
version = "0.0.2"
edition = "2021"
license = "MPL 2.0"
repository = "https://github.com/filiptibell/lune"
description = "A Luau script runner"
keywords = ["cli", "lua", "luau", "scripts"]
categories = ["command-line-interface"]

[dependencies]
anyhow = { version = "1.0.68" }
clap = { version = "4.1.1", features = ["derive"] }
mlua = { version = "0.8.7", features = ["luau", "async", "serialize"] }
reqwest = { version = "0.11.13", features = ["gzip", "deflate"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = { version = "1.0.91" }
tokio = { version = "1.24.2", features = ["full"] }
